version: '2'
 
services:
    ambassador:
      image: cpuguy83/docker-grand-ambassador
      container_name: ambassador
      hostname: ambassador
      network_mode: "bridge"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      command: "-name jenkins -name gitlab "
 
    jenkins:
      image: jenkins/jenkins
      container_name: jenkins
      hostname: jenkins
      network_mode: "bridge"
      links:
        - "ambassador:gitlab"
      ports:
        - "8085:8080"
        - "50000:50000"
      volumes:
        - /var/jenkins_home
 
    gitlab:
        image: gitlab/gitlab-ce
        container_name: gitlab
        hostname: gitlab
        restart: always
        network_mode: bridge
        links:
          - "ambassador:jenkins"
        ports:
           - "443:443"
           - "8050:80"
           - "22:22"
        volumes:
          - ~/gitlab/config:/etc/gitlab
          - ~/gitlab/logs:/var/log/gitlab
          - ~/gitlab/data:/var/opt/gitlab
